# advanced-model-monitoring.yaml
$schema: https://azuremlschemas.azureedge.net/latest/monitorSchedule.schema.json
name: synthetic-cli-deployment-2-adv
display_name: Synthetic predictive maintenance model monitoring
description: Example model monitoring setup with advanced configurations

trigger:
  # perform model monitoring activity daily at 3:15am
  type: recurrence
  frequency: day #can be minute, hour, day, week, month
  interval: 1 # #every day
  schedule: 
    hours: 16 # at 3am
    minutes: 0 # at 15 mins after 3am

create_monitor:
  compute: 
    instance_type: standard_e4s_v3
    runtime_version: '3.3'
  monitoring_target:
    ml_task: classification
    endpoint_deployment_id: azureml:synthetic-predictive-maintenance-endpoint:cli-deployment-1
  
  monitoring_signals:
    advanced_data_drift: # monitoring signal name, any user defined name works
      type: data_drift
      # target_dataset is optional. By default target dataset is the production inference data associated with Azure Machine Learning online endpoint
      reference_data:
        input_data:
          path: azureml:synthetic-mltable-training@latest # use training data as comparison baseline
          type: mltable
        data_context: training
        target_column_name: failure
      features: 
        top_n_feature_importance: 3 # monitor drift for top 3 features
      metric_thresholds:
        numerical:
          jensen_shannon_distance: 0.01
        categorical:
          pearsons_chi_squared_test: 0.02
    advanced_data_quality:
      type: data_quality
      # target_dataset is optional. By default target dataset is the production inference data associated with Azure Machine Learning online depoint
      reference_data:
        input_data:
          path: azureml:synthetic-mltable-training@latest
          type: mltable
        data_context: training
      # features: # monitor data quality for 3 individual features only
      #   - feature_A
      #   - feature_B
      #   - feature_C
      metric_thresholds:
        numerical:
          null_value_rate: 0.05
        categorical:
          out_of_bounds_rate: 0.03

    feature_attribution_drift_signal:
      type: feature_attribution_drift
      # production_data: is not required input here
      # Please ensure Azure Machine Learning online endpoint is enabled to collected both model_inputs and model_outputs data
      # Azure Machine Learning model monitoring will automatically join both model_inputs and model_outputs data and used it for computation
      reference_data:
        input_data:
          path: azureml:synthetic-mltable-training@latest
          type: mltable
        data_context: training
        target_column_name: failure
      metric_thresholds:
        normalized_discounted_cumulative_gain: 0.9
  
  alert_notification:
    emails:
      - hehein@microsoft.com
      - hendrik.hein@microsoft.com