name: sklearn-with-mltable
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pandas
  - scipy
  - numpy
  - pip:
      - scikit-learn-intelex #==2023.2.1
      - wheel~=0.38.1
      - azureml-core
      - azureml-defaults
      - azureml-mlflow
      - azureml-telemetry
      - azureml-automl-common-tools
      - scikit-learn~=1.2.2
      - joblib~=1.2.0
      - mltable
      # vulnerabilities
      - cryptography>=41.0.3
      - certifi >= 2023.07.22
      - requests >= 2.31.0
