$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command

name: train_model
display_name: Train Model 

code: ./train_model

environment: azureml:sklearn-with-mltable@latest

is_deterministic: true

inputs:
  train_data:
    type: mltable
    description: Input file (MLTable, parquet)
  validation_data:
    type: mltable
    description: Input file (MLTable, parquet)
outputs:
  trained_model:
    type: mlflow_model
    description: Output model filepath (will be written as mlflow files)

command: >-
  python train_model.py
  --train_data ${{inputs.train_data}}
  --validation_data ${{inputs.validation_data}}
  --trained_model ${{outputs.trained_model}}
