$schema: https://azuremlschemas.azureedge.net/latest/monitorSchedule.schema.json
name: synthetic-monitor-24-02-21-08-45
display_name: Synthetic predictive maintenance example model monitoring
description: Example model monitoring setup with advanced configurations

trigger:
  type: recurrence
  frequency: week  #can be minute, hour, day, week, month
  interval: 1 # every 3 days
  schedule:
      hours: 7
      minutes: 0
      week_days: monday

create_monitor:

  compute: 
    instance_type: standard_e4s_v3
    runtime_version: "3.3"

  monitoring_target:
    ml_task: classification
    model_id: azureml:synthetic-pred-maintenance@latest

  monitoring_signals:

    advanced_data_drift:
      type: data_drift
      reference_data:
        input_data:
          path: azureml:synthetic-mltable-training-train@latest
          type: uri_file
        data_context: training
        target_column_name: failure
      production_data:
        input_data:
          path: azureml:synthetic-urifolder-production-outputs@latest
          type: uri_folder
        data_context: model_inputs
        pre_processing_component: azureml:preprocess_synthetic_data_spark:2024-02-12-13-39-42-1586336
        data_window:
            lookback_window_offset: P0D
            lookback_window_size: P7D
      features: 
        top_n_feature_importance: 10
      alert_enabled: true
      metric_thresholds:
        numerical:
          normalized_wasserstein_distance: 0.1
        categorical:
          jensen_shannon_distance: 0.1

    advanced_data_quality:
      type: data_quality
      reference_data:
        input_data:
          path: azureml:synthetic-mltable-training-train@latest
          type: mltable
        target_column_name: failure
        data_context: training
      production_data:
        input_data:
          path: azureml:synthetic-urifolder-production-outputs@latest
          type: uri_folder
        data_context: model_inputs
        pre_processing_component: azureml:preprocess_synthetic_data_spark:2024-02-12-13-39-42-1586336
        data_window:
            lookback_window_offset: P0D
            lookback_window_size: P7D
      alert_enabled: true
      features:
        top_n_feature_importance: 10
      metric_thresholds:
        numerical:
          data_type_error_rate: 0.01
          null_value_rate: 0.01
          out_of_bounds_rate: 0.01
        categorical:
          data_type_error_rate: 0.01
          null_value_rate: 0.01
          out_of_bounds_rate: 0.01

    advanced_prediction_drift:
      type: prediction_drift
      production_data:
        input_data:
          path: azureml:synthetic-urifolder-production-outputs@latest
          type: uri_folder
        data_context: model_inputs
        pre_processing_component: azureml:preprocess_synthetic_data_spark:2024-02-12-13-39-42-1586336
        data_window:
            lookback_window_offset: P0D
            lookback_window_size: P7D
      reference_data:
        input_data:
          path: azureml:synthetic-mltable-training-train@latest
          type: mltable
        data_context: training
      alert_enabled: true
      metric_thresholds:
        numerical:
          normalized_wasserstein_distance: 0.1
        categorical:
          jensen_shannon_distance: 0.1


  alert_notification:
    emails:
      - hehein@microsoft.com