$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json

name: cli-deployment-2 # cd pipeline will override this name

description: >-
  Deploy a synthetic data  predictive maintenance classification model with custom logging to an online endpoint

tags: {"demo": "synthetic predictive maintenance", "datacollection": "custom"}

endpoint_name: synth-pred-maint-endpoint
model: azureml:synthetic-pred-maintenance@latest
environment: azureml:synthetic-predmaintenance-inference@latest
code_configuration:
  code: synthetic-deployment-custom # custom logging
  scoring_script: score.py
instance_type: Standard_F2s_v2 # alternatives: Standard_DS3_v2, Standard_F2s_v2
instance_count: 1
app_insights_enabled: true

data_collector:
  rolling_rate: hour
  sampling_rate: 1
  collections:
    model_inputs:
      enabled: 'true'
      # data: azureml:diabetes-cli-deployment-inputs:1
    model_outputs:
      enabled: 'true'
      # data: azureml:diabetes-cli-deployment-outputs:1
    model_inputs_outputs:
      enabled: 'true'
      # data: azureml:diabetes-cli-deployment-inputs-outputs:1
