channels:
- conda-forge
dependencies:
- python=3.8
- pip=22.3.1
- pip:
  - mlflow
  - scikit-learn==1.2.2
  - cloudpickle==2.2.1
  - psutil==5.9.4
  - pandas==2.0.0
  - azureml-inference-server-http
  - azureml-defaults==1.38.0
  - azureml-ai-monitoring~=0.1.0b1
name: mlflow-env